# ________________________________________________
#
#        AKANE EMBEDS FILE
#
# Embed Colors Accept Color Names
# (Red, GREEN etc.) and HEX (#f1f1f1, #dddddd etc.)
#
# For new Line use \n
#
# ________________________________________________

# Title of every Embed
title: "üìú Akane - Embed Configuration"
# Title of Suggestion Embed
suggestion_title: "üí° Suggestion"
# Footer of Every Embed
footer: "¬© 2023 Akane Bot | Codey by XSaitoKungX"
# Embed Color for Errors or Negative Responses
error_color: "Red"
# Embed Color for Success or Positive Responses
success_color: "Green"
# Embed Color for other situations
general_color: "Yellow"
# Suggestions Embed
suggestion:
  title: "üåü New Suggestion"
  color: "Yellow"
  # Valid Placeholders: <author>, <suggestions>, <date>, <yes_vote>, <no_vote>
  description: "A new suggestion has been submitted."
  footer: true 
  thumbnail: true
  # Valid Placeholders: <author>, <suggestions>, <date>, <yes_vote>, <no_vote>
  # To use just description set to fields: []
  fields:
    - title: "Author"
      description: "<author>"
    - title: "Suggestion"
      description: "<suggestion>"
    - title: "Upvotes"
      description: "<yes_vote>"
    - title: "Downvotes"
      description: "<no_vote>"
# Calculate Embed
calculate:
  title: "üßÆ Calculator"
  color: "Yellow"
  # Valid Placeholders: <expression>, <result>
  description: "Your math problem has been calculated."
  footer: true 
  thumbnail: false
  # Valid Placeholders: <expression>, <result>
  # To use just description set to fields: []
  fields:
    - title: "Expression"
      description: "<expression>"
    - title: "Result"
      description: "```js\n<result>\n```"
user_info:
  title: "üë§ User Information"
  # Valid Placeholders: <user>, <joinedAt>, <roles>, <createdAt>, <highestRole>, <username>, <id> 
  description: "Information about <user>."
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <user>, <joinedAt>, <roles>, <createdAt>, <highestRole>, <username>, <id> 
  # To use just description set to fields: []
  fields:
    - title: "Username"
      description: "<username>"
    - title: "ID"
      description: "<id>"
    - title: "Joined At"
      description: "<joinedAt>"
    - title: "Created At"
      description: "<createdAt>"
    - title: "Highest Role"
      description: "<highestRole>"
role_info:
  title: "üõ°Ô∏è Role Information"
  # Valid Placeholders: <role>, <id>, <mentionable>, <createdAt>, <color>, <position>, <permissions>
  description: "Information about <role>."
  color: "#4CAAFF"
  footer: true
  # Role Icon Thumbnail (If exists)
  thumbnail: true
  # Valid Placeholders: <role>, <id>, <mentionable>, <createdAt>, <color>, <position>, <permissions> 
  # To use just description set to fields: []
  fields:
    - title: "Role ID"
      description: "<id>"
    - title: "Created At"
      description: "<createdAt>"
    - title: "Color"
      description: "<color>"
    - title: "Position"
      description: "<position>"
    - title: "Permissions"
      description: "<permissions>"
# ServerInfo Embed
server_info:
  title: "üè∞ Server Information"
  # Valid Placeholders: <name>, <id>, <createdAt>, <channels>, <roles>, <bots>, <members>, <online>,
  # <boostCount>
  description: "Information Server <name>."
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <name>, <id>, <createdAt>, <channels>, <roles>, <bots>, <members>, <online> 
  # <boostCount>
  # To use just description set to fields: []
  fields:
    - title: "Guild Name"
      description: "<name>"
    - title: "ID"
      description: "<id>"
    - title: "Creation Date"
      description: "<createdAt>"
    - title: "Member Count"
      description: "<members>"
# Invites Joined Logging Embed
invites_joined:
  # Valid Placeholders: <username>
  title: "üì• User Joined"
  # Valid Placeholders: <createdAt>, <joinsInvites>, <regularInvites>, <leavesInvites>,
  # <totalInvites>, <invitedBy>, <user>, <members>.
  description: "<user> has joined, invited by <invitedBy>\n<invitedBy> now has <regularInvites> regular invites."
  color: "Green"
  footer: true
# Invites Joined Left Embed
invites_left:
  # Valid Placeholders: <username> 
  title: "üì§ User Left"
  # Valid Placeholders: <createdAt>, <joinsInvites>, <regularInvites>, <leavesInvites>,
  # <totalInvites>, <invitedBy>, <user>, <members>.
  description: "<user> has left, invited by <invitedBy>\n<invitedBy> now has <regularInvites> regular invites."
  color: "Red"
  footer: true
welcome:
  title: "üéâ New Member"
  # Valid Placeholders: <user>, <members>, <invitedBy>, <createdAt>
  description: "<user> has joined server, we now have <members> members.\nInvited by: <invitedBy>"
  color: "#4CAAFF"
  footer: true
  thumbnail: true
# Leave Message
leave:
  title: "üëã Member Left"
  # Valid Placeholders: <user>, <members>, <invitedBy>, <createdAt>
  description: "<user> has left server, we now have <members> members.\nInvited by: <invitedBy>"
  color: "#4CAAFF"
  footer: true
  thumbnail: true
# 8ball Embed
eightball:
  title: "üé± 8ball"
  # Question Field
  question: "Question"
  # Answer Field
  answer: "Answer"
  color: "#4CAAFF"
  footer: true
  thumbnail: true
# Backup Embed
backup:
  load:
    title: "üìÇ Load Backup"
    # Question Field
    description: "Choose option to apply."
    # Answer Field
    buttons:
      all: "Load All"
      roles: "Load Roles"
      channels: "Load Channels"
    color: "#4CAAFF"
    footer: true
# Help Menu Embed
help:
  title: "üöÄ ¬∑ Help Menu"
  # Valid Placeholders: <commandsCount>, <prefix>
  description: "To view Commands of specific Category use Select Menu\n\n>>> 1. Member Commands\n2. Utility\n3. Moderation\n4. Music\n5. Fun\n6. Giveaway\n7. Administration"
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <commandsCount>, <prefix>
  # To use just description set to fields: []
  fields: []
# Command Info Embed
command_info:
  title: "üöÄ ¬∑ Information About Command"
  # Valid Placeholders: <name>, <description>, <usage>, <category> & <prefix>
  description: ""
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <name>, <description>, <usage>, <category> & <prefix>
  # To use just description set to fields: []
  fields:
    - title: "Command Name"
      description: "`<name>`"
    - title: "Description"
      description: "`<description>`"
    - title: "Usage"
      description: "`<prefix><usage>`"
    - title: "Category"
      description: "`<category>`"
# Level Embed
level:
  title: "üìä Level"
  # Valid Placeholders: <user>, <level>, <rank> (Leaderboard), <percentage>, <xp>, <xpNeeded> & <progress> (bar)
  description: "**User:** <user>\n**Level:** <level>\n**Rank:** #<rank>\n**Progress:** <progress> `(<percentage>%)`"
  color: "#4CAAFF"
  footer: true
  thumbnail: false
  # Valid Placeholders: <user>, <level>, <rank> (Leaderboard), <percentage>, <xp>, <xpNeeded> & <progress> (bar)
  # To use just description set to fields: []
  fields: []
# Giveaway Embed
giveaway:
  title: "üéÅ Giveaway"
  # Valid `laceholders: <reward>, <hoster>, <remaining>, <winnerCount>, <requirements>,
  # <winners> (just for endDescription)
  description: "**Reward:** <reward>\n**Hosted by:** <hoster>\n**Remaining Time:** <remaining>\n**Number of Winners:** <winnerCount><requirements>"
  endDescription: "**Reward:** <reward>\n**Hosted by:** <hoster>\n**Remaining Time:** <remaining>\n**Number of Winners:** <winnerCount>\n**Winners:** <winners><requirements>"
  color: "Yellow"
  footer: true
# Giveaway Confirm Embed
gw_confirm:
  title: "üéÅ Giveaway Setup"
  # Valid Placeholders: <joinsInvites>, <leavesInvites>, <regularInvites>, <invites>, <rank>, <history>, <user>
  description: "Are this Giveaway Details Good? Confirm by clicking Button.\nDuration: <duration>\nChannel: <channel>\nWinners: <winners>\nMessages: <messages>\nInvites: <invites>\nPrize: <prize>"
  color: "Yellow"
  footer: true
# Verification Embed
verification:
  title: "üîê Verification Required"
  fail_title: "‚ùå Verification Failed"
  success_title: "‚úÖ Verification Success"
  description: ">>> In order to gain access to the Server you'll need to verify yourself first.\n\n**Select option from Dropdown which has value ||<code>||, you have 60 seconds**."
  description_captcha: ">>> In order to gain access to the Server you'll need to verify yourself first.\n\nType in the right phrase you see on image."
  fail_description: ">>> You didn't pass verification in time. Use `-verify` in DM to restart Verification (once per 2 minutes)."
  success_description: ">>> You have been verified successfully, enjoy."
  color: "Yellow"
  footer: true
auto_mod:
  caps:
    title: "üîí Anti Caps-Lock"
    description: "Hey <user>, you cannot use that much of CapsLock in message."
    footer: true
    color: "Red"
  links:
    title: "üîí Anti Links"
    description: "Hey <user>, you cannot send links!"
    footer: true
    color: "Red"
  bad_words:
    title: "üîí Bad Words"
    description: "Hey <user>, don't swear, watch your language!"
    footer: true
    color: "Red"
  invites:
    title: "üîí Anti Invites"
    description: "Hey <user>, you cannot post server invites here!"
    footer: true
    color: "Red"
  spam:
    title: "üîí Anti Spam"
    description: "Hey <user>, please slow down, you're sending messages too fast!"
    footer: true
    color: "Red"
economy:
  jobs_main:
    title: "üíº Job Menu"
    # For no description, leave empty
    description: "These are list of all options you can do."
    fields:
    - title: "‚Ä¢ Apply for Job"
      description: "To start working you'll first need job `work apply <name>`"
    - title: "‚Ä¢ List of All Jobs"
      description: "To get list of all jobs do `work jobs`"
    - title: "‚Ä¢ Work"
      description: "To start working your job do `work`"
    - title: "‚Ä¢ Quit Job"
      description: "To Quit your current job do `work quit`"
    color: "Yellow"
    footer: true
  jobs_list:
    title: "üìã Job List"
    # For no description, leave empty
    description: "These are all jobs you can work, use command `work` to start."
    # Format for Embed Fields
    # Valid Placeholders: <jobName>, <minSalary>, <maxSalary> and <cooldown>
    fields_format:
      name: "<jobName>"
      value: " ‚Ä¢ Min. Salary: $<minSalary>\n ‚Ä¢ Max. Salary: $<maxSalary>\n ‚Ä¢ Cooldown: <cooldown>"
    color: "Yellow"
    footer: true
ticket:
  title: "üì© Welcome to your Ticket"
  description: "Hello <user>, this is your ticket,\n\nYou can ask whatever you want here and someone will get back to you shortly.\n"
  color: "Yellow"
  footer: true
  thumbnail: ""
panel:
  title: "üì© Ticket Panel"
  description: "Hey! If you need help or have a question, use button to open Ticket and someone will get back to you shortly."
  color: "Yellow"
  footer: true
  thumbnail: ""
# MCServer Command Embed
mc_server:
  title: "üéÆ Minecraft Server Info"
  # Valid Placeholders: <ip>, <port>, <hostname>, <online>, <players>, <maxPlayers>, <version>, <plugins>,
  # <software>
  description: "Information about <hostname>."
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <ip>, <port>, <hostname>, <online>, <players>, <maxPlayers>, <version>, <plugins>,
  # <software>
  # To use just description set to fields: []
  fields:
    - title: "IP"
      description: "<ip>"
    - title: "Port"
      description: "<port>"
    - title: "Online"
      description: "<online>"
    - title: "Players"
      description: "<players>/<maxPlayers>"
    - title: "Version"
      description: "<version>"
channel_info:
  title: "üì∫ Channel Info"
  # Valid Placeholders: <name>, <id>, <topic>, <type>, <position>, <parent>, <lastMessageId>, <nsfw> 
  description: "Information about <name>."
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <name>, <id>, <topic>, <type>, <position>, <parent>, <lastMessageId>, <nsfw> 
  # To use just description set to fields: []
  fields:
    - title: "Parent"
      description: "<parent>"
    - title: "ID"
      description: "<id>"
    - title: "Type"
      description: "<type>"
    - title: "Position"
      description: "#<position>"
boosters:
  title: "üöÄ Server Boosters"
  # Valid Placeholders: <boostersList>, <boostersCount> (number of boosters), <boostsCount> (number of boosts),
  # <boosterRole>, <guildName>
  description: "Server has a total of **<boostsCount>** boosts"
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <boostersList>, <boostersCount> (number of boosters), <boostsCount> (number of boosts),
  # <boosterRole>, <guildName>
  # To use just description set to fields: []
  fields:
    - title: "Boosters List"
      description: "<boostersList>"
poll:
  title: "üìä Poll"
  # Valid Placeholders: <author>, <question>, <options>, <startedTime>
  description: "New Poll has been started by <author>"
  color: "#4CAAFF"
  footer: true
  thumbnail: true
  # Valid Placeholders: <author>, <question>, <options>, <startedTime>
  # To use just description set to fields: []
  fields:
    - title: "Question"
      description: "<question>"
    - title: "Options List"
      description: "<optionsList>"
poll_ended:
  title: "üìä Poll Ended"
  # Valid Placeholders: <author>, <question>, <options>, <resultsList>, <endedTime>
  description: "Poll started by <author> has ended"
  color: "#AA4A44"
  footer: true
  thumbnail: true
  # Valid Placeholders: <author>, <question>, <options>, <resultsList>, <endedTime>
  # To use just description set to fields: []
  fields:
    - title: "Question"
      description: "<question>"
    - title: "Poll Results"
      description: ">>> <resultsList>"
    - title: "Ended"
      description: "<endedTime>"
punishments:
  banned_dm:
    title: "‚õî Punishment - Banned"
    # Valid Placeholders: <guild>, <user>, <staff> & <reason>
    description: "You've been banned from <guild>"
    color: "#4CAAFF"
    footer: true
    thumbnail: true
    # Valid Placeholders: <guild>, <user>, <staff> & <reason>
    # To use just description set to fields: []
    fields:
      - title: "Banned by"
        description: "<staff>"
      - title: "Reason"
        description: "<reason>"
  muted_dm:
    title: "üîá Punishment - Muted"
    # Valid Placeholders: <guild>, <staff>, <reason> & <duration>
    description: "You've been muted on <guild>"
    color: "#4CAAFF"
    footer: true
    thumbnail: true
    # Valid Placeholders: <guild>, <staff>, <reason> & <duration>
    # To use just description set to fields: []
    fields:
      - title: "Muted by"
        description: "<staff>"
      - title: "Reason"
        description: "<reason>"
      - title: "Duration"
        description: "<reason>"
  kicked_dm:
    title: "üë¢ Punishment - Kicked"
    # Valid Placeholders: <guild>, <staff> & <reason>
    description: "You've been kicked from <guild>"
    color: "#4CAAFF"
    footer: true
    thumbnail: true
    # Valid Placeholders: <guild>, <staff> & <reason>
    # To use just description set to fields: []
    fields:
      - title: "Kicked by"
        description: "<staff>"
      - title: "Reason"
        description: "<reason>"
  warned_dm:
    title: "‚ö†Ô∏è Punishment - Warned"
    # Valid Placeholders: <guild>, <staff>, <reason> & <warns>
    description: "You've been warned on <guild>"
    color: "#4CAAFF"
    footer: true
    thumbnail: true
    # Valid Placeholders: <guild>, <staff>, <reason> & <warns>
    # To use just description set to fields: []
    fields:
      - title: "Warned by"
        description: "<staff>"
      - title: "Total Warnings"
        description: "<warns>"
      - title: "Reason"
        description: "<reason>"